**Numpy**

Numpy is used to create the data in the form of dimensions

It is work with dimension

In [ ]:
import numpy as np

In [ ]:
len(dir(np))

595

**Built_in_functions in Numpy that we need to learn for data science community**

* array
* arange
* reshape
* reshape(-1,1) and reshape(1,-1)
* shape
* ndim
* size
* linespace
* zeros
* ones
* full
* eye
* transpose
* concatenate
* ravel
* random -> random
* randint
* randn
* rand
* max
* min
* sum
* argmax
* argmin
* axis = 1
* axis = 0

In [ ]:
# array -> it is used to create data in the form of dimensions

a = np.array([10,20,30,40])

print(a)

print(a.ndim)

print(a.shape)

[10 20 30 40]
1
(4,)


In [ ]:
a = np.array([10,20,30,40])

print(a[1])

20


In [ ]:
a = np.array([ [10,20,30] , [50,60,70] , [100,200,300] ])

print(a)

print(a.ndim)

print(a.shape)

print(a.size)

[[ 10  20  30]
 [ 50  60  70]
 [100 200 300]]
2
(3, 3)
9


In [ ]:
print(a[2][0])

100


In [ ]:
print(a[1][1])

60


In [ ]:
# arange -> it is used to create 1D data -> with n-1 logic

a = np.arange(11,21)
print(a)
print(a.ndim)

[11 12 13 14 15 16 17 18 19 20]
1


In [ ]:
# converting 1D data -> 2D data

a = np.arange(1,61)
print(a)
print(a.ndim)

print('---------------------------')

b = a.reshape(10,6)
print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
---------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2


In [ ]:
print(b[3][3])

22


In [ ]:
# converting 1D data -> 3D data

a = np.arange(1,61)
print(a)
print(a.ndim)

print('--------------------------')

b = a.reshape(5,2,6)
print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
--------------------------
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3


In [ ]:
print(b[2][1][3])

34


In [ ]:
# converting 1D data 3D data

a = np.arange(1,61)
print(a)
print(a.ndim)

print('--------------------------')

b = a.reshape(2,5,6)
print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
--------------------------
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]
  [25 26 27 28 29 30]]

 [[31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]
  [49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3


In [ ]:
print(b[1][1][3])

40


In [ ]:
b[0][3][0]

19

In [ ]:
a = np.array([10,20,30,50,100])
print(a)

print(a.ndim)

print(a.shape)

[ 10  20  30  50 100]
1
(5,)


In [ ]:
# reshape

a = np.array([10,20,30,50,100])
print(a)

b = a.reshape(5,1)
print(b)
print(b.ndim)
print(b.shape)

[ 10  20  30  50 100]
[[ 10]
 [ 20]
 [ 30]
 [ 50]
 [100]]
2
(5, 1)


In [ ]:
a = np.array([10,20,30,50,100])
print(a.shape)

b = a.reshape(-1,1)

print(b)
print(b.shape)

(5,)
[[ 10]
 [ 20]
 [ 30]
 [ 50]
 [100]]
(5, 1)


In [ ]:
a = np.array([10,20,30,50,100])
print(a.shape)

b = a.reshape(1,-1)

print(b)
print(b.shape)

(5,)
[[ 10  20  30  50 100]]
(1, 5)


In [ ]:
# linespace -> divide into bins in given range

a = np.linspace(10,20,6)
print(a)

[10. 12. 14. 16. 18. 20.]


In [ ]:
# zeros
# defaulty numpy has float64 data type

a = np.zeros((5,4),dtype=np.int64)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# ones

a = np.ones((5,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In Deep Learning

* Black colour image means -> zeros
* White colour area in the image means -> ones

In [ ]:
# full

a = np.full((5,4) , 9)
a

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [ ]:
# eye -> it is nothing but identity matrix
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# ravel -> it will convert any dims into 1D

a = np.array([ [10,20,30] , [50,60,70] , [100,200,300] ])
print(a)

b = a.ravel()
print(b)


[[ 10  20  30]
 [ 50  60  70]
 [100 200 300]]
[ 10  20  30  50  60  70 100 200 300]


In [ ]:
# Transpose -> rows to columns and columns to rows

a = np.array([ [10,20,30] , [50,60,70] , [100,200,300] ])
print(a)

print('--------------------------------')

b = a.T
print(b)

[[ 10  20  30]
 [ 50  60  70]
 [100 200 300]]
--------------------------------
[[ 10  50 100]
 [ 20  60 200]
 [ 30  70 300]]


In [ ]:
# concatenation => adding

a = np.array([ [10,20,30] , [50,60,70] , [100,200,300] ])
print(a)

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

print('----------------------------------')

c = np.concatenate((a,b))
print(c)

[[ 10  20  30]
 [ 50  60  70]
 [100 200 300]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------
[[ 10  20  30]
 [ 50  60  70]
 [100 200 300]
 [  1   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
# random -> randint

a = np.random.randint(10,50,3)
a

array([29, 11, 40])

In [ ]:
a = np.random.randint(10,50)
a

36

In [ ]:
# random ->randn

a = np.random.randn(5,4)
a

array([[-0.34373102,  1.91336337,  0.12883493, -2.72493708],
       [-1.54047604, -0.79726722, -1.44367652, -1.20881556],
       [-0.72717198,  1.12608204,  1.61551768,  0.01302428],
       [-0.43651225,  0.21576885, -1.21756676,  0.00564215],
       [-0.3341766 , -0.35610168, -0.0519119 ,  0.23028076]])

In [ ]:
# random -> rand -> there is no negative values but in between 0-1 only

a = np.random.rand(5,4)
a

array([[0.55693009, 0.22875993, 0.73558938, 0.2585304 ],
       [0.57410184, 0.17902057, 0.85290692, 0.09225502],
       [0.28159338, 0.61954876, 0.34820923, 0.40448249],
       [0.80635918, 0.26818817, 0.65094573, 0.75666399],
       [0.66487209, 0.20962338, 0.82761983, 0.37687142]])

In [ ]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [ ]:
np.sum(a)

100

In [ ]:
np.min(a)

10

In [ ]:
np.max(a)

40

In [ ]:
a = np.array([ [10,3,13] , [4,8,1] , [6,12,3] ])
print(a)

[[10  3 13]
 [ 4  8  1]
 [ 6 12  3]]


In [ ]:
np.max(a)

13

In [ ]:
np.min(a)

1

In [ ]:
np.sum(a)

60

In [ ]:
# argmax -> it will give index

np.argmax(a)

2

In [ ]:
np.argmin(a)

5

In [ ]:
# axis = 1 -> rows
# axis = 0 -> columns

In [ ]:
np.max(a,axis=1)

array([13,  8, 12])

In [ ]:
np.max(a,axis=0)

array([10, 12, 13])

In [ ]:
np.sum(a,axis=1)

array([26, 13, 21])

In [ ]:
np.sum(a,axis=0)

array([20, 23, 17])

In [ ]:
np.argmax(a,axis=1)

array([2, 1, 1])

In [ ]:
np.argmax(a,axis=0)

array([0, 2, 0])

In [ ]:
np.argmin(a,axis=0)

array([1, 0, 1])

In [ ]:
np.argmin(a,axis=1)

array([1, 2, 2])